name: Docker CI for Production

on:
  push:
    tags:
      - v\d+\.\d+\.\d+

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        thread: [platform]
        include:
          - thread: platform
            repository: $(echo $GITHUB_REPOSITORY | cut -d / -f 2)
            tag-prefix: ''

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install pnpm
        run: |
          npm i -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: build
        run: |
          pnpm run build:prod

      - name: Get the ref
        id: get_ref
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: build the image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{matrix.repository}}:${{ matrix.tag-prefix }}${{ steps.get_ref.outputs.VERSION }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/${{matrix.repository}}:${{ matrix.tag-prefix }}${{ steps.get_ref.outputs.VERSION }}
