name: Docker Image CI for Development

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        thread: [platform]
        include:
          - thread: platform
            name: $(echo $GITHUB_REPOSITORY | cut -d / -f 2 )
            tag: latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: build the image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{matrix.name}}:${{matrix.tag}}

    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/${{matrix.name}}:${{matrix.tag}}
