name: Docker Image CI for Development

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  build_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        thread: [platform]
        include:
          - thread: platform
            repository: $(echo $GITHUB_REPOSITORY | cut -d / -f 2)
            tag: latest

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install pnpm
        run: |
          npm i -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: build
        run: |
          pnpm run build:prod

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build the image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{matrix.repository}}:${{matrix.tag}}

      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/${{matrix.repository}}:${{matrix.tag}}


      # - name: Build and push Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{secrets.DOCKER_USER}}/${{matrix.repository}}:${{matrix.tag}}
